/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Mayara
 */
public class TelaReceita extends javax.swing.JFrame {

    /**
     * Creates new form TelaReceita
     */
    public TelaReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Receita.");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("INDENTIFICAÇÃO MÉDICA.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 180, 250, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("34 Anos.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 240, 60, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/uuuuuuu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 570, 290, 90);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel4.setText("SEXO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 300, 40, 15);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("RECEITUÁRIO MÉDICO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 140, 300, 21);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel8.setText("IDADE: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 50, 15);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel9.setText("ENDEREÇO: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 260, 60, 15);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel10.setText("DATA DE NASCIMENTO:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 280, 140, 15);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel11.setText("NOME: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 220, 130, 15);

        jLabel17.setText("Medicação: ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 470, 640, 50);

        jLabel27.setText("Posologia:    Tomar 1 comprimido de 8 em 8 horas, conforme necessário para dor ou febre. 5 DIAS");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(30, 430, 590, 50);

        jLabel18.setText("Posologia:   ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 490, 590, 50);

        jLabel19.setText("Medicação:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 410, 260, 50);

        jLabel23.setText("Posologia:  ");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 430, 260, 50);

        jLabel24.setText("Posologia:  ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(30, 430, 260, 50);

        jLabel25.setText("Posologia:   Tomar 5 ml (1 colher de chá) três vezes ao dia. 5 DIAS");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 490, 590, 50);

        jLabel26.setText("Medicação: Xarope de Bromexina 4 mg/5 ml.");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 470, 640, 50);

        jLabel16.setText("Medicação: Paracetamol 500 mg.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 410, 260, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Dra. Eduarda Campos.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 220, 130, 14);

        jLabel70.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel70.setText("CRM:");
        getContentPane().add(jLabel70);
        jLabel70.setBounds(360, 280, 25, 15);

        jLabel71.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel71.setText("789012");
        getContentPane().add(jLabel71);
        jLabel71.setBounds(400, 280, 250, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("20/05/90 ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(150, 280, 60, 14);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 480, 650, 50);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Av. das Palmeiras, 456, Bairro Verde - SBC");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(90, 260, 250, 14);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Femenino.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 300, 60, 14);

        jLabel63.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel63.setText("INDENTIFICAÇÃO DO PACIENTE.");
        getContentPane().add(jLabel63);
        jLabel63.setBounds(20, 180, 250, 30);

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(20, 420, 650, 50);

        jLabel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel65);
        jLabel65.setBounds(350, 170, 330, 170);

        jLabel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel66);
        jLabel66.setBounds(10, 170, 330, 170);

        jLabel68.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel68.setText("NOME COMPLETO:");
        getContentPane().add(jLabel68);
        jLabel68.setBounds(20, 220, 130, 15);

        jLabel72.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel72.setText("Av. Pereira Barreto, 1479 - SBC");
        getContentPane().add(jLabel72);
        jLabel72.setBounds(430, 250, 250, 14);

        jLabel73.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel73.setText("ENDEREÇO: ");
        getContentPane().add(jLabel73);
        jLabel73.setBounds(360, 250, 60, 15);

        jLabel69.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel69.setText("Camila da Silva Souza.");
        getContentPane().add(jLabel69);
        jLabel69.setBounds(120, 220, 130, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telareceita.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 690, 970);

        jLabel20.setText("Posologia:  ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 450, 260, 50);

        jLabel21.setText("Medicação:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 430, 260, 50);

        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(20, 480, 650, 50);

        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(20, 420, 650, 50);

        jLabel30.setText("Posologia:  ");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(30, 450, 260, 50);

        jLabel31.setText("Medicação:");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(30, 430, 260, 50);

        jLabel33.setText("Medicação: Paracetamol 500 mg.");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(30, 410, 260, 50);

        jLabel34.setText("Medicação: Xarope de Bromexina 4 mg/5 ml.");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(30, 470, 640, 50);

        jLabel35.setText("Posologia:   Tomar 5 ml (1 colher de chá) três vezes ao dia. 5 DIAS");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(30, 490, 590, 50);

        jLabel36.setText("Posologia:  ");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(30, 450, 260, 50);

        jLabel37.setText("Medicação: ");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(30, 470, 640, 50);

        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel38);
        jLabel38.setBounds(20, 420, 650, 50);

        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel39);
        jLabel39.setBounds(20, 480, 650, 50);

        jLabel40.setText("Medicação: Paracetamol 500 mg.");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(30, 410, 260, 50);

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel41);
        jLabel41.setBounds(20, 420, 650, 50);

        jLabel42.setText("Posologia:  ");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(30, 450, 260, 50);

        jLabel43.setText("Medicação:");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(30, 430, 260, 50);

        jLabel44.setText("Posologia:   ");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(30, 490, 590, 50);

        jLabel45.setText("Medicação: Xarope de Bromexina 4 mg/5 ml.");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(30, 470, 640, 50);

        jLabel46.setText("Medicação:");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(30, 430, 260, 50);

        jLabel47.setText("Medicação: Paracetamol 500 mg.");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(30, 410, 260, 50);

        jLabel48.setText("Posologia:   Tomar 5 ml (1 colher de chá) três vezes ao dia. 5 DIAS");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(30, 490, 590, 50);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setText("20/05/90 ");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(590, 200, 60, 14);

        jLabel50.setText("Medicação: Paracetamol 500 mg.");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(30, 410, 260, 50);

        jLabel51.setText("Medicação:");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(30, 430, 260, 50);

        jLabel52.setText("Medicação:");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(30, 430, 260, 50);

        jLabel53.setText("Posologia:   ");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(30, 490, 590, 50);

        jLabel54.setText("Posologia:   Tomar 5 ml (1 colher de chá) três vezes ao dia. 5 DIAS");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(30, 490, 590, 50);

        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel55);
        jLabel55.setBounds(20, 420, 650, 50);

        jLabel56.setText("Posologia:  ");
        getContentPane().add(jLabel56);
        jLabel56.setBounds(30, 450, 260, 50);

        jLabel57.setText("Medicação: Xarope de Bromexina 4 mg/5 ml.");
        getContentPane().add(jLabel57);
        jLabel57.setBounds(30, 470, 640, 50);

        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel58);
        jLabel58.setBounds(20, 420, 650, 50);

        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel59);
        jLabel59.setBounds(20, 480, 650, 50);

        jLabel60.setText("Medicação: ");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(30, 470, 640, 50);

        jLabel61.setText("Medicação: Paracetamol 500 mg.");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(30, 410, 260, 50);

        jLabel62.setText("Posologia:  ");
        getContentPane().add(jLabel62);
        jLabel62.setBounds(30, 450, 260, 50);

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel32.setText("INDENTIFICAÇÃO DO PACIENTE");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(20, 180, 250, 30);

        jLabel64.setText("jLabel64");
        getContentPane().add(jLabel64);
        jLabel64.setBounds(20, 160, 43, 16);

        jMenu1.setText("Menu Inicial");
        jMenu1.setToolTipText("");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Menu Inicial.");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(702, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        new TelaMenu ().setVisible (true);
        dispose ();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
