/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Mayara
 */
public class Teladecadastro extends javax.swing.JFrame {

    /**
     * Creates new form Teladecadastro
     */
    public Teladecadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro.");
        getContentPane().setLayout(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(610, 130, 310, 30);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(360, 130, 150, 30);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(770, 290, 150, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(650, 210, 210, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(360, 290, 210, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(440, 210, 200, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(360, 210, 70, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "MG", "BA" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(880, 212, 72, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(360, 50, 310, 30);

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(710, 50, 210, 30);

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(590, 290, 150, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(650, 360, 130, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(360, 360, 130, 30);

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cadastrar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 420, 120, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(700, 370, 280, 130);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(700, 250, 280, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 170, 280, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 90, 280, 100);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 170, 280, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(480, 170, 280, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 30, 280, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 110, 280, 100);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 100, 280, 100);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(690, 260, 280, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(700, 80, 280, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(600, 100, 280, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 30, 280, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 30, 280, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(610, 90, 280, 100);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(660, 170, 280, 100);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(690, 320, 280, 100);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(530, 250, 280, 90);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(340, 240, 280, 110);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(340, 250, 280, 110);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(530, 250, 280, 90);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(620, 260, 280, 110);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(450, 250, 280, 90);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(340, 320, 280, 100);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(520, 320, 280, 100);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brancolinha.jpg"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(700, 360, 280, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrotel.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 460);

        setSize(new java.awt.Dimension(1009, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          new LoginTela().setVisible (true);
          dispose ();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teladecadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teladecadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teladecadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teladecadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teladecadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
